package org.studyeasy;


class Brackets {
	//Object o=new Object();
	//private Object lock="lock";
	private static String threadCode;
	
	

	synchronized static public void generate(String threadCode) {
		 
		 
				for(int i=0;i<10;i++) {
					if(i<5) {
						System.out.print("[");
					}else {
						System.out.print("]");
					}
					}
					System.out.println("generated by thread "+threadCode);
				
		 }

	
}

public class App {

	public static void main(String[] args) {
		Brackets bracket1=new Brackets();
		Brackets bracket2=new Brackets();
		//bracket.generate();
		
		new Thread(new Runnable(){

			@Override
			public void run() {
				for(int i=0;i<5;i++) {
						Brackets.generate("thread 1");
					//System.out.println("th1");
				}
			
				
			}
			
		}).start();

		new Thread(new Runnable(){

			@Override
			public void run() {
				for(int i=0;i<5;i++) {
					Brackets.generate("thread 2");
				}
			
				
			}
			
		}).start();
	}

}
